name: Go

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Check out code into the Go module directory
      uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: 1.20.3

    - name: Go version
      run: go version

    - name: Get dependencies
      run: go mod download

    - name: Run tests
      env:
        OPENAI_TOKEN: ${{ secrets.OPENAI_TOKEN }}
        GOOGLE_TOKEN: ${{ secrets.GOOGLE_TOKEN }}
        GOOGLE_ENGINE_ID: ${{ secrets.GOOGLE_ENGINE_ID }}
      run: go test -v ./...

    - name: Notify reviewer if tests pass
      if: ${{ success() }}
      run: echo "Tests passed. Notify the reviewer."
      # 此处可以添加通知 reviewer 的具体操作，例如发送邮件、发送 Slack 消息等。
